### PR TITLE
fix: #17 wrong url path for vision_wasm

### PR DESCRIPTION
**Pull request by jonkad**
update @mediapipe/tasks-vision to v0.10.6

### CODE REVIEW

**Comment by huynguyengl99** [comment]
It looks like the upgrade in @mediapipe/tasks-vision can work. 🤝

**Comment by CSantosM** [comment]
This PR works, can be merged? :)

**Comment by tony-betamind** [comment]
What are we waiting for :V

**Comment by lukasIO** [comment]
As the CLA wasn't signed on this one, I went ahead and merged #20 instead

**Pull request closed without merging**
